version: '3'

services:
  django:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - db:/app/db
      - ./static:/app/static
      - ./sock:/app/sock
    env_file:
      - .env

volumes:
  db: