# Generated by Django 3.0.7 on 2020-06-03 17:37

from django.db import migrations, models
import urlshortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.URLField(max_length=255)),
                ('slug', models.CharField(default=urlshortener.models.create_slug, max_length=11, unique=True)),
                ('ref_type', models.CharField(choices=[('header', 'Header'), ('js', 'JavaScript')], default='header', max_length=6)),
            ],
        ),
    ]
